//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nov4PracEntities1 : DbContext
    {
        public Nov4PracEntities1()
            : base("name=Nov4PracEntities1")
        {
        }

        public static Nov4PracEntities1 _context;

        public static Nov4PracEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new Nov4PracEntities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Архив_Блюда> Архив_Блюда { get; set; }
        public virtual DbSet<Архив_Приготовление> Архив_Приготовление { get; set; }
        public virtual DbSet<Архив_Продукты> Архив_Продукты { get; set; }
        public virtual DbSet<Архив_Рецепты> Архив_Рецепты { get; set; }
        public virtual DbSet<Архив_СоставБлюд> Архив_СоставБлюд { get; set; }
        public virtual DbSet<Блюда> Блюда { get; set; }
        public virtual DbSet<Приготовление> Приготовление { get; set; }
        public virtual DbSet<Продукты> Продукты { get; set; }
        public virtual DbSet<Рецепты> Рецепты { get; set; }
        public virtual DbSet<СоставБлюд> СоставБлюд { get; set; }
    }
}
