//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Архив_Блюда
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Архив_Блюда()
        {
            this.Архив_Приготовление = new HashSet<Архив_Приготовление>();
            this.Архив_Рецепты = new HashSet<Архив_Рецепты>();
            this.Архив_СоставБлюд = new HashSet<Архив_СоставБлюд>();
        }
    
        public int Код_блюда { get; set; }
        public string Название_блюда { get; set; }
        public string Вид_блюда { get; set; }
        public Nullable<int> Выход { get; set; }
        public byte[] Изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Архив_Приготовление> Архив_Приготовление { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Архив_Рецепты> Архив_Рецепты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Архив_СоставБлюд> Архив_СоставБлюд { get; set; }
    }
}
