//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукты()
        {
            this.СоставБлюд = new HashSet<СоставБлюд>();
        }
    
        public int Код_продукта { get; set; }
        public string Название_продукта { get; set; }
        public Nullable<int> Калорийность { get; set; }
        public Nullable<int> Вес_продукта { get; set; }
        public Nullable<int> Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставБлюд> СоставБлюд { get; set; }
    }
}
