//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставБлюд
    {
        public int Код_состава { get; set; }
        public Nullable<int> Код_блюда { get; set; }
        public Nullable<int> Код_продукта { get; set; }
    
        public virtual Блюда Блюда { get; set; }
        public virtual Продукты Продукты { get; set; }
    }
}
